<?php

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */
class WPVCSetting {
	
	private $wp_vc_setting_options;
	
	public function __construct() {
		add_action( 'admin_menu', array( $this, 'wp_vc_setting_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'wp_vc_setting_page_init' ) );
	}

	public function wp_vc_setting_add_plugin_page() {
		add_options_page(
			'WP VC Setting', // page_title
			'WP VC Setting', // menu_title
			'manage_options', // capability
			'wp-vc-setting', // menu_slug
			array( $this, 'wp_vc_setting_create_admin_page' ) // function
		);
	}

	public function wp_vc_setting_create_admin_page() {
		$this->wp_vc_setting_options = get_option( 'wp_vc_setting_option_name' ); ?>
		<div class="wrap">
			<h2>WP VC Setting</h2>
			<p>Setting page. Add you Affiliate key. You can find your key <a href="https://partners.vcommission.com/publisher/#!/tools/api-key" target="_blank">here.</a></p>
			<form method="post" action="options.php">
				<?php
					settings_fields( 'wp_vc_setting_option_group' );
					do_settings_sections( 'wp-vc-setting-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function wp_vc_setting_page_init() {
		register_setting(
			'wp_vc_setting_option_group', // option_group
			'wp_vc_setting_option_name', // option_name
			array( $this, 'wp_vc_setting_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'wp_vc_setting_setting_section', // id
			'', // title
			array( $this, 'wp_vc_setting_section_info' ), // callback
			'wp-vc-setting-admin' // page
		);

		add_settings_field(
			'api_key_0', // id
			'API Key', // title
			array( $this, 'api_key_0_callback' ), // callback
			'wp-vc-setting-admin', // page
			'wp_vc_setting_setting_section' // section
		);
	}

	public function wp_vc_setting_sanitize($input) {
		
		$sanitary_values = array();
		$is_valid = $this->wp_vc_validate_api_key($input);
		if(!$is_valid){
			return;
		}else{
			if ( isset( $input['api_key_0'] ) ) {
				$sanitary_values['api_key_0'] = sanitize_text_field( $input['api_key_0'] );
			}
			return $sanitary_values;
		}
	}

	public function wp_vc_validate_api_key($input)
	{
		$vaild = true;
		
		if(empty($input['api_key_0']))
		{
			$valid = false;
			add_settings_error('wp_vc_error_messages','wp_vc_error_messages_empty','API Key cannot be empty','error');
		}else{
			$api_key = $input['api_key_0'];
			
			$response = wp_remote_get('https://vcm.api.hasoffers.com/Apiv3/json?api_key='.$api_key.'&Target=Affiliate_Affiliate&Method=findById');
			$body_response = wp_remote_retrieve_body( $response );
			
			$response = json_decode($body_response, true);

			if(isset($response['response']['status']) && $response['response']['status']===1){
				$valid = true;
			}else{
				add_settings_error('wp_vc_error_messages','wp_vc_error_messages_empty','API call failed'.(isset($response['response']['errorMessage'])?' ('.$response['response']['errorMessage'].')':'').'','error');
				$valid = false;
			}
		}
		return $valid;
	}
	
	public function wp_vc_setting_section_info() {
		// Nothing to do
	}
	
	public function api_key_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="wp_vc_setting_option_name[api_key_0]" id="api_key_0" value="%s">',
			isset( $this->wp_vc_setting_options['api_key_0'] ) ? esc_attr( $this->wp_vc_setting_options['api_key_0']) : ''
		);
	}

}
if ( is_admin() )
	$wp_vc_setting = new WPVCSetting();

/* 
 * Retrieve this value with:
 * $wp_vc_setting_options = get_option( 'wp_vc_setting_option_name' ); // Array of All Options
 * $api_key_0 = $wp_vc_setting_options['api_key_0']; // API Key
 */